### ISSUE TITLE
add molecule entity type

### ISSUE THREAD

**Issue by jorge-computedfield** [dynotx/liminal-orm#52]
There's an entity type that's not included in the current version: molecules.
They are part of the normal registry but are only available if a separate licence is bought for "chemistry" (not sure what name Benchling gives to this).
My understanding is that this would have to be added here: https://github.com/dynotx/liminal-orm/blob/main/liminal/enums/__init__.py#L2 and all the references to these enums updated.

**Comment by ndamania00** [comment]
The default fields are id, source_id, name, canonical_smiles. The rest is exactly the same as say custom_entities (i.e: you can add the same field types as far as I can tell, choose between registry IDs / names, naming template, etc).
In case you are not familiar with SMILES: https://openbabel.org/docs/FileFormats/Canonical_SMILES_format.html

**Comment by ndamania00** [comment]
For this PR, we are adding molecule as an entity type. This includes...
- Adding to the [entity type enum ](https://github.com/dynotx/liminal-orm/blob/main/liminal/enums/benchling_entity_type.py#L4)
- Adding to the [BenchlingFolderItemType](https://github.com/dynotx/liminal-orm/blob/main/liminal/enums/benchling_folder_item_type.py)
- Adding to entity type [mappers](https://github.com/dynotx/liminal-orm/blob/main/liminal/mappers.py)
  - @jorge-computedfield could you find the FolderItemType and Sequence type for the mappers? I will link the query below
- Adding molecule as a mixin, so that users can create different molecule entities with the base fields - [here](https://github.com/dynotx/liminal-orm/blob/main/liminal/orm/mixins.py)
  - Fields in mixin: canonical_smiles
  - @jorge-computedfield could you confirm that columns in [base_model](https://github.com/dynotx/liminal-orm/blob/main/liminal/orm/base_model.py) + `canonical_smiles` cover all non-custom fields?
- Add to generate_files mappers

**Comment by ndamania00** [comment]
code to get all schemas, where you can search for a molecule entity type and find `FolderItemType` and `SequenceType`
```
from liminal.entity_schemas.tag_schema_models import TagSchemaModel
from liminal.connection import BenchlingService, BenchlingConnection

benchling_service = BenchlingService(test_connection, use_internal_api=True)
data = TagSchemaModel.get_all_json(benchling_service)
```

**Comment by aarushgarg1110** [comment]
Currently working on this issue

**Comment by jorge-computedfield** [comment]
@ndamania00, @aarushgarg1110

- Could you find the FolderItemType and Sequence type for the mappers?

See below an example for one schema:

"folderItemType": "molecule"
"sequenceType": null

```
{
    "iconId": "small-molecule",
    "id": "ts_xxxxxxxx",
    "name": "[Training] Compound",
    "folderItemType": "molecule",
    "sequenceType": null,
    "shouldCreateAsOligo": false,
    "sqlIdentifier": "compound",
    "archiveRecord": null,
    "allFields": [],
    "fields": [],
    "isContainable": false,
    "constraint": null,
    "authParentOption": "FOLDER",
    "mixtureSchemaConfig": null,
    "includeRegistryIdInChips": false,
    "batchSchemaId": null,
    "childEntitySchemaSummaries": [
        {
            "iconId": "basic_folder_item",
            "id": "ts_xxxxxxxx",
            "name": "[Training] Compound Batch",
            "folderItemType": "basic_folder_item",
            "sequenceType": null,
            "shouldCreateAsOligo": false,
            "sqlIdentifier": "compound_batch",
            "archiveRecord": {
                "purpose": "Made in error"
            }
        }
    ],
    "containableType": "NONE",
    "prefix": "T-COMP",
    "hoistedTagSchemaGraphs": [],
    "labelingStrategies": [
        "DELETE_NAMES",
        "IDS_FROM_NAMES",
        "NEW_IDS"
    ],
    "nameTemplateFields": [],
    "nameTemplateParts": [],
    "registryId": "src_xxxxxxxx",
    "resultSchema": null,
    "shouldOrderNamePartsBySequence": false,
    "showResidues": false,
    "useRandomOrgAlias": false,
    "useOrganizationCollectionAliasForDisplayLabel": false,
    "permissions": {
        "readable": true,
        "writable": true,
        "appendable": false,
        "admin": true,
        "archivable": true,
        "unarchivable": false,
        "definitionListable": true,
        "definitionEditable": true,
        "definitionDeletable": true,
        "objectsCreatable": true,
        "objectsRegisterable": true
    }
}
```

- Could you confirm that columns in [base_model](https://github.com/dynotx/liminal-orm/blob/main/liminal/orm/base_model.py) + canonical_smiles cover all non-custom fields?

Yes, that’s my understanding of the model for molecules. If you can think of any way I can provide a more definitive answer, please let me know.
